### ISSUE TITLE
addon slug

### ISSUE THREAD

**Issue by marcetad** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#1]
Hi Max,

First of all, nice addon. Working good. 

Made an automation (with node-red) to receive a telegram message when stock is available. 
Now trying to shutdown the addon after the message is send. Next day at a specific time to start the addon. The problem is the current slug of the addon. In my case the slug is  "f1c878cb-tgtg-ha-mqtt-bridge". Looks like the problem are the dash symbols. Is it possible to replace the dash symbols by underscore's? (when i try to shutdown a different addon, 243ffc37_syncthing no problems occur)

Would it be possible to increase the polling time? Looks likes it polls every 30 seconds. I would like to run the addon just for +-10 minutes and increase the polling time. This because of some popular 'magix boxes' ;)

**Comment by MaxWinterstein** [comment]
> Is it possible to replace the dash symbols by underscore's?

Well, not that easy. this would be like a new addon afaik and leave everyone with some dead version.  But, maybe I can help you with the shutdown problem? How are you doing it?



> Would it be possible to increase the polling time? Looks likes it polls every 30 seconds. I would like to run the addon just for +-10 minutes and increase the polling time. This because of some popular 'magix boxes' ;)

Yeah, definitely! 30s was some development test, and never changed it ;) will adjust to something like 5 minutes and allow overwrite via config. Next release ✌️

**Comment by marcetad** [comment]
> 

> Well, not that easy. this would be like a new addon afaik and leave everyone with some dead version. But, maybe I can help you with the shutdown problem? How are you doing it?

Just tried with a HA automation:

```yaml
alias: Stop TGT addon
description: 'stop addon'
trigger:
  - platform: time
    at: '19:00'
condition: []
action:
  - service: hassio.addon_stop
    data:
      addon: f1c878cb-tgtg-ha-mqtt-bridge
mode: single
```
This is not working, While when I try(with execute now button) a different addon it works.
```yaml
alias: Stop TGT addon
description: 'stop addon'
trigger:
  - platform: time
    at: '19:00'
condition: []
action:
  - service: hassio.addon_stop
    data:
      addon: 243ffc37_syncthing
mode: single
```
> 
> Yeah, definitely! 30s was some development test, and never changed it ;) will adjust to something like 5 minutes and allow overwrite via config. Next release ✌️

Nice! Thanks in advance.

**Comment by MaxWinterstein** [comment]
I guess
```yaml
addon: f1c878cb-tgtg-ha-mqtt-bridge
```
should more be like
```yaml
addon: f1c878cb_tgtg-ha-mqtt-bridge
```

At least if i look at the url and at portainer:

![image](https://user-images.githubusercontent.com/5927148/104661806-a0bba780-56c9-11eb-95f8-bb3dc6acd64a.png)
![image](https://user-images.githubusercontent.com/5927148/104661864-c6e14780-56c9-11eb-91cc-e5fbab3e230d.png)

Or was your example some typo?

> Nice! Thanks in advance.

I created the release `1.0.0` that has some adjustable sleep timer. It now allows setting the pause between the pull intervals in minutes. Spoiler: `0.1` is also a valid value 😉

**Comment by marcetad** [comment]
Sorry, typo. I checked the slug in the terminal addon; type 'ha addons'.
![tgtt](https://user-images.githubusercontent.com/60152777/104706695-be196180-571b-11eb-99c9-b31e6bd859a4.png)

![syncthing](https://user-images.githubusercontent.com/60152777/104706694-bd80cb00-571b-11eb-880c-10cab6baac74.png)

did you try to execute the automation?
I tried stopping an addon with the automation provided earlier;
a0d7b954_adguard
243ffc37_syncthing
core_configurator
a0d7b954_grafana
all working.

not working:
f1c878cb_tgtg-ha-mqtt-bridge
f1c878cb_eufy-ha-mqtt-bridge

no other addons running with a dash in the slug so cannot test with other addons. If its not possible to fix for this addon then its all fine. Maybe good to keep in mind if you release a new addon.

Version 1.0.0. running fine 👍 thanks

**Comment by MaxWinterstein** [comment]
i took some deep dive into that problem, and it seems like this is some core related problem with slugs containing a dash.

I opened some issue at the offical repository https://github.com/home-assistant/core/issues/45185 which also mentions some workaround by using the community provided ssh addon.

I installed it, added some random password and disabled port 22. Now this call seems to work for me:

```yaml
service: hassio.addon_stdin
data:
  addon: a0d7b954_ssh
  input: ha addon stop f1c878cb_tgtg-ha-mqtt-bridge
```
