### ISSUE TITLE
Automatically create Push-Notifications for favorited Stores

### ISSUE THREAD

**Issue by bigbasti** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#106]
Hello Everyone,

i am fiddling around with this plugin and basically everything works well.

I am wondering if it is possible to automate creating a push notification automation for all favorited stores.

Right now I have to update the automation for the notification manually every time I add a new favorite store in the tagt app.

It is possible to read all created sensors from the favorites:
```
{%- for state in states -%}
    {%- if (state.entity_id.startswith('sensor.toogoodtogo_'))-%}
      {{state.entity_id}},
    {%- endif -%}
{%- endfor -%}
```

Is it somehow possible to feed this directly into the notifications automation so I just need to add the store to the favorites inside the tgtg app and automatically receive notifications for it?

Thanks

**Comment by MaxWinterstein** [comment]
indeed, good idea. 

I searched a bit, and found this anwser to a simila question:
> You can solve that by creating a template sensor which has a count of sensors below 15.5 degrees as it’s state, and a list of entities which are below 15.5 degrees as an attribute.



https://community.home-assistant.io/t/add-support-for-wildcards-in-automation-trigger-entity-id/152337/6

---  

I did some playaround, and this automation might be a good start:

```yaml
alias: TooGoodToGo Food Available
description: "Push a notification as soon as food is available"
trigger:
  - platform: event
    event_type: state_changed
    event_data:
      domain: sensor
condition:
  - condition: template
    value_template: "{{ trigger.event.data.entity_id.startswith('sensor.toogoodtogo_')}}"
action:
  - service: notify.max
    data: {}
    data_template:
      message: >-
        {{ trigger.event.data.old_state.name }} has changed from {{
        trigger.event.data.old_state.state }} to {{
        trigger.event.data.new_state.state }}
mode: single
```

need some filtering for like `old_state.state > new_state.state` but I think this might be a good start.

With all that developing i just rate limited myself again, so i cant test further 😉
